name: todo
services:
  app:
    build: ./app
    pull_policy: build
    image: node-app
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  postgres:
    image: postgres:13-alpine
    healthcheck:
      test: ["CMD-SHELL","pg_isready -q -U postgres"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_interval: 15s
    env_file:
      - ./postgres.env
    volumes:
      - todo-db:/var/lib/postgresql/
    networks:
      - app-net

networks:
  app-net:

